services:
    bot:
        build: .
        image: tradeflow:latest
        environment:
            - BOT_TOKEN
            - kalshi_events_API
            - poly_events_API
            - poly_trades_API
            - poly_walletProfile_API
            - kalshi_trades_API
        dns:
            - 8.8.8.8
            - 1.1.1.1
